### ISSUE TITLE
LINE公式アカウントの友だち追加画面の表示

### ISSUE THREAD

**Issue by kapi819** [kapi819/portfolio_2#129]
- 実装したいもの・解決したいもの(なるべく小さい粒度で記載してください)
　友達追加画面を、LINE認証実行後に自動表示させること。

- 疑問点
　現在、本リリースに実装予定のLINE通知機能を実装しております。LINE通知機能のロジックは、以下を参照して書き終え、`ReminderNotificationJob.perform_now`を通じた動作確認が終了しておりますが、友達追加が別途必要と気づき、実装しております。
　以下、LINE Developersの公式ドキュメントを参照し、`bot_prompt`クエリパラメータを付けてユーザーをリダイレクトすることで、自動的にLINE公式アカウントを友だち追加するかどうか確認する画面が表示出来るとありました。そのため、以下画像の通り、devise.rb部分に、
```
Devise.setup do |config|
  config.omniauth :line, ENV['LINE_KEY'], ENV['LINE_SECRET'],
                  bot_prompt: 'aggressive',　←追記部分
end
```
`bot_prompt`部分を、従前環境変数が記載されていた部分に追記しましたが、友達追加が自動的に画面表示されず、検証ツールのNetwork部分にあるRequest URLに追記部分が反映されていませんでした。

- 実装する際に参考にした資料
　以下、qiitaの記事を参照しましたが、sorcery等を使用した設定は記載されていましたが、deviseを使用した記事はありませんでした。

LINE通知機能の参照資料↓
https://qiita.com/rk2530/items/9bea7317065151c5c588
LINE Developersの公式ドキュメント↓
https://developers.line.biz/ja/docs/line-login/link-a-bot/#redirect-users
devise修正箇所Gyazo↓
[![Image from Gyazo](https://i.gyazo.com/74953022950d86e0fe1d194b406319c0.png)](https://gyazo.com/74953022950d86e0fe1d194b406319c0)
検証ツールのNetwork部分Gyazo↓
[![Image from Gyazo](https://i.gyazo.com/d4b6597812e3dd00793a127b5867e5ca.png)](https://gyazo.com/d4b6597812e3dd00793a127b5867e5ca)
bot_promptの参照資料↓
https://qiita.com/tkm_kj/items/3c825822867e607bc733

**Comment by kenchasonakai** [comment]
> 以下、qiitaの記事を参照しましたが、sorcery等を使用した設定は記載されていましたが、deviseを使用した記事はありませんでした。

記事を探して見つからないのであればなかなか難しいと思いますので他のLINE通知を実装している人のUIや記事を探してみてなにか代替できないかとか工夫できないか考えてみるとよいのではないでしょうか

**Comment by kapi819** [comment]
> > 以下、qiitaの記事を参照しましたが、sorcery等を使用した設定は記載されていましたが、deviseを使用した記事はありませんでした。
> 
> 記事を探して見つからないのであればなかなか難しいと思いますので他のLINE通知を実装している人のUIや記事を探してみてなにか代替できないかとか工夫できないか考えてみるとよいのではないでしょうか

ご返信ありがとうございます。
承知しました、再度確認します。
