### ISSUE TITLE
"issueベースの開発”レビュー依頼

### ISSUE THREAD

**Issue by kapi819** [kapi819/portfolio_2#48]
# 概要
## GitHubProject
https://github.com/users/kapi819/projects/1

### 実装予定の機能
**MVP**

- [ ] ユーザー登録機能（LINE認証）
- [ ] ログイン機能
- [ ] ログアウト機能
- [ ] マイページ機能
- [ ] プロフィール表示及び編集機能
- [ ] 冷え性の質問機能（6問）
- [ ] 質問結果に応じた結果判定機能
- [ ] 結果に応じた改善策のリコメンド機能
- [ ] Xへのポスト機能

**本リリース**

- [ ] 日々の目標設定機能
- [ ] カレンダーでのスケジュール管理機能
- [ ] 目標設定に応じたリマインド機能（LINE通知）
- [ ] その日の情報記録機能(基礎体温・体重・体脂肪・体調・気分)
- [ ] 上記情報の分析機能

### 必要なページ

- [ ] TOP画面（機能紹介）
- [ ] ログイン画面(LINE認証)
- [ ] 新規登録画面
- [ ] 質問画面
- [ ] 結果判定画面
- [ ] リコメンド画面
- [ ] 目標設定画面
- [ ] 目標達成の記録画面(メイン画面)
- [ ] スケジュール管理画面
- [ ] マイページ画面
- [ ] プロフィール画面
- [ ] その日の情報記録画面
- [ ] 分析表示画面

**Comment by Tsuchiya2** [comment]
<img width="762" alt="image" src="https://github.com/kapi819/portfolio_2/assets/61481161/1bfa0b9e-33dd-4951-aaad-3f10664e2190">


projectssにアクセスしましたが、看板・issue・ストーリーポイントが確認できませんでした。
カリキュラムを確認いただいて、上記が確認できる状態でご提出をお願いいたします。

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。
