### ISSUE TITLE
"MVPリリース"レビュー依頼

### ISSUE THREAD

**Issue by kapi819** [kapi819/portfolio_2#93]
## 各種情報
サービス名：Chill Out
サービスURL：https://portfolio-2-xm41.onrender.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] ユーザー登録機能（LINE認証）
- [x] ログイン機能
- [x] ログアウト機能
- [ ] マイページ機能
- [ ] プロフィール表示及び編集機能
- [x] 冷え性の質問機能（6問）
- [x] 質問結果に応じた結果判定機能
- [ ] 結果に応じた改善策のリコメンド機能
- [x] Xへのポスト機能

## READMEレビュー時から変更した機能
- [ ] マイページ機能
- [ ] プロフィール表示及び編集機能
- [ ] 結果に応じた改善策のリコメンド機能
については、面談時に本リリース時にということでしたので、MVP時には実装しておりません。

**Comment by Tsuchiya2** [comment]
LINEログインした状態で診断を実施すると、6回答をした時点でエラー画面が出てしまうのですが、ご確認いただけますでしょうか。

[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/3d384dfa1aaf2acaa6c0210cde38c2ae.gif)](https://startup-technology.gyazo.com/3d384dfa1aaf2acaa6c0210cde38c2ae)

**Comment by kapi819** [comment]
エラーが発生しており、大変申し訳ありません。
　修正させていただきましたので、ご確認の程よろしくお願いします。

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
